AppQuinto/AppQuinto/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;

namespace AppQuinto.Models
{
    public class Cliente
    {
        [Display(Name = "Código")]
        public int? idCli { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório")]

        public string nomeCli { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.DateTime)]

        public DateTime DataNasc { get; set; }
    }
}

AppQuinto/AppQuinto/Models/ErrorViewModel.cs
namespace AppQuinto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppQuinto/AppQuinto/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;

namespace AppQuinto.Models
{
    public class Usuario
    {
        [Display(Name = "Código")]
        public int? idUsu { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório")]

        public string nomeUsu { get; set; }

        [Display(Name = "Cargo")]
        [Required(ErrorMessage = "O campo Cargo é obrigatório")]

        public string Cargo { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.DateTime)]

        public DateTime DataNasc { get; set; }  
    }
}

AppQuinto/AppQuinto/Controllers/ClienteController.cs
using AppQuinto.Models;
using AppQuinto.Repository;
using AppQuinto.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppQuinto.Controllers
{
    public class ClienteController : Controller
    {
        private IClienteRepository _clienteRepository;
        public ClienteController(IClienteRepository clienteRepository)
        {
            _clienteRepository = clienteRepository;
        }
        public IActionResult Index()
        {
            return View(_clienteRepository.ObterTodosClientes());
        }
        [HttpGet]
        public IActionResult CadastrarCliente()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarCliente(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _clienteRepository.Cadastrar(cliente);
            }
            return View();
        }
        [HttpGet]
        public IActionResult AtualizarCliente(int id)
        {
            return View(_clienteRepository.ObterCliente(id));
        }
        [HttpPost]
        public IActionResult AtualizarCliente(Cliente cliente)
        {
            _clienteRepository.Atualizar(cliente);

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult DetalhesCliente(int id)
        {
            return View(_clienteRepository.ObterCliente(id));
        }
        [HttpPost]
        public IActionResult DetalhesCliente(Cliente cliente)
        {
            _clienteRepository.Atualizar(cliente);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ExcluirCliente(int id)
        {
            _clienteRepository.Excluir(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AppQuinto/AppQuinto/Controllers/HomeController.cs
using AppQuinto.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppQuinto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppQuinto/AppQuinto/Controllers/UsuarioController.cs
using AppQuinto.Models;
using AppQuinto.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppQuinto.Controllers
{

    public class UsuarioController : Controller
    {
        private IUsuarioRepository _usuarioRepository;
        public UsuarioController (IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        public IActionResult Index()
        {
            return View(_usuarioRepository.ObterTodosUsuarios());
        }
        [HttpGet]                                                    
        public IActionResult CadastrarUsuario()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarUsuario(Usuario usuario)
        {
            if(ModelState.IsValid)
            {
                _usuarioRepository.Cadastrar(usuario);
            }
            return View();
        }
        [HttpGet]
        public IActionResult AtualizarUsuario(int id)
        {
            return View(_usuarioRepository.ObterUsuario(id));
        }
        [HttpPost]
        public IActionResult AtualizarUsuario(Usuario usuario)
        {
            _usuarioRepository.Atualizar(usuario);

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult DetalhesUsuario(int id)
        {
            return View(_usuarioRepository.ObterUsuario(id));
        }
        [HttpPost]
        public IActionResult DetalhesUsuario(Usuario usuario)
        {
            _usuarioRepository.Atualizar(usuario);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ExcluirUsuario(int id)
        {
            _usuarioRepository.Excluir(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AppQuinto/AppQuinto/Views/Cliente/AtualizarCliente.cshtml
@model AppQuinto.Models.Cliente

@{
    ViewData["Title"] = "AtualizarCliente";
}

<h1>Atualizar Cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarCliente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idCli" class="control-label"></label>
                <input asp-for="idCli" class="form-control" />
                <span asp-validation-for="idCli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nomeCli" class="control-label"></label>
                <input asp-for="nomeCli" class="form-control" />
                <span asp-validation-for="nomeCli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppQuinto/AppQuinto/Views/Cliente/CadastrarCliente.cshtml
@model AppQuinto.Models.Cliente

@{
    ViewData["Title"] = "CadastrarCliente";
}

<h1>Cadastrar Cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarCliente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nomeCli" class="control-label"></label>
                <input asp-for="nomeCli" class="form-control" />
                <span asp-validation-for="nomeCli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppQuinto/AppQuinto/Views/Cliente/DetalhesCliente.cshtml
@model AppQuinto.Models.Cliente

@{
    ViewData["Title"] = "DetalhesCliente";
}

<h1>Detalhes Cliente</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idCli)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idCli)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nomeCli)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nomeCli)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNasc)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
</div>

AppQuinto/AppQuinto/Views/Cliente/Index.cshtml
@model IEnumerable<AppQuinto.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Clientes</h1>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">@Html.DisplayNameFor(model => model.idCli)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.nomeCli)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.DataNasc)</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Cliente cliente in Model) 
            {
                <tr>
                    <td>@cliente.idCli) </td> 
                    <td>@cliente.nomeCli) </td>
                    <td>@cliente.DataNasc.ToString("dd/MM/yyyy"))</td>
                    <td>
                        <button type="button" class="btn btn-warning botaoatualiza">
                            @Html.ActionLink("Editar", "AtualizarCliente", new { id = cliente.idCli })
                        </button>
                        <button type="button" class="btn btn-warning botaodetalhes">
                            @Html.ActionLink("Detalhes", "DetalhesCliente", new { id = cliente.idCli}) 
                        </button>
                        <button type="button" class="btn btn-warning botaoexcluir">
                            @Html.ActionLink("Excluir", "ExcluirCliente", new { id = cliente.idCli })
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<p><a class="btn btn-primary" asp-action="CadastrarCliente" asp-controller="Cliente">Cadastrar</a></p>

AppQuinto/AppQuinto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppQuinto/AppQuinto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppQuinto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppQuinto.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppQuinto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Cadastros de Usuários</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Cadastros de Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppQuinto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppQuinto/AppQuinto/Views/Usuario/AtualizarUsuario.cshtml
@model AppQuinto.Models.Usuario

@{
    ViewData["Title"] = "AtualizarUsuario";
}

<h4>Editar o Usuário</h4> <hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarUsuario">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idUsu" class="form-control" />

            <div class="form-group">
                <label asp-for="nomeUsu" class="control-label"></label>
                <input asp-for="nomeUsu" class="form-control" />
                <span asp-validation-for="nomeUsu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <input asp-for="Cargo" class="form-control" />
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input type="date" asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts { @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppQuinto/AppQuinto/Views/Usuario/CadastrarUsuario.cshtml
@model AppQuinto.Models.Usuario

@{
    ViewData["Title"] = "CadastrarUsuario";
}

<h1>Área de Cadastro</h1>

<h4>Cadastrar Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarUsuario">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nomeUsu" class="control-label"></label>
                <input asp-for="nomeUsu" class="form-control" />
                <span asp-validation-for="nomeUsu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <input asp-for="Cargo" class="form-control" />
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input type="date" asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppQuinto/AppQuinto/Views/Usuario/DetalhesUsuario.cshtml
@model AppQuinto.Models.Usuario

@{
    ViewData["Title"] = "DetalhesUsuario";
}

<h1>Detalhes do Usuario</h1>
<br />
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.idUsu) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.idUsu)  </dd>
            
        <dt class="col-sm-2">  @Html.DisplayNameFor(model => model.nomeUsu)  </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.nomeUsu) </dd>
            
        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.Cargo) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.Cargo)</dd>

        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.DataNasc)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.DataNasc) </dd>
    </dl>
</div>
<br />
<div>
    <button type="button" class="btn btn-warning">
        @Html.ActionLink("Editar", "AtualizarUsuario", new { id = Model.idUsu})
    </button>
    <button type="button" class="btn btn-secondary">
        @Html.ActionLink("Voltar", "Index")
    </button>
</div>

AppQuinto/AppQuinto/Views/Usuario/Index.cshtml
@model IEnumerable<AppQuinto.Models.Usuario>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Usuarios</h1>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col"> @Html.DisplayNameFor(model => model.idUsu) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.nomeUsu) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.Cargo)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.DataNasc) </th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Usuario usuario in Model) 
            {
                <tr>
                    <td>@usuario.idUsu)</td>
                    <td>@usuario.nomeUsu</td>
                    <td>@usuario.Cargo</td>
                    <td>@usuario.DataNasc.ToString("dd/MM/yyyy")</td>
                    <td>
                        <button type="button" class="btn btn-warning botaoatualiza">
                             @Html.ActionLink("Editar", "AtualizarUsuario", new { id = usuario.idUsu })
                        </button>

                        <button type="button" class="btn btn-secondary botaodetalhes">
                            @Html.ActionLink("Detalhes", "DetalhesUsuario", new { id = usuario.idUsu })
                         </button>

                        <button type="button" class="btn btn-danger botaoexcluir">
                            @Html.ActionLink("Excluir", "ExcluirUsuario", new { id = usuario.idUsu },
                                        new { onclick = "return confirm('Deseja realmente desativar?');"})
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<p><a class="btn btn-primary" asp-action="CadastrarUsuario" asp-controller="Usuario">Cadastrar</a></p>